### ISSUE TITLE
Clean up RNN branch

### ISSUE THREAD

**Issue by APJansen** [GrainLearning/grainLearning#13]
- Remove unnecessary files
- Remove/merge duplicate boilerplate files
- Change file structure to merge with grainlearning
- Update requirements
- etc

**Comment by APJansen** [comment]
With poetry we probably want to make the rnn dependencies optional, as they are quite heavy (mainly tensorflow).

**Comment by APJansen** [comment]
I manually updated pyproject.toml adding the rnn dependencies. For the versions I checked what the latest was and used that, but that might not be necessary. Then ran `poetry lock --no-update` to add these to the lock file without upgrading versions of other packages. Then tested installing with `poetry install`, but there is an issue with tensorflow, specifically: Unable to find installation candidates for tensorflow-io-gcs-filesystem (0.27.0) ([related issue](https://github.com/tensorflow/io/issues/1617))
Likely this is because I'm on a (arm) mac, replacing tensorflow with tensorflow-macos fixed it for me, everything now installs. But this needs to be fixed for everyone somehow..

**Comment by APJansen** [comment]
It runs now, as long as the data is present at `grainlearning/rnn/data/sequences.hdf5`. Wandb creates a folder inside `rnn/`.

**Comment by APJansen** [comment]
Another todo: generate the documentation, and probably for that to work we have to pick one convention for docstrings as currently we're using different ones.

**Comment by luisaforozco** [comment]
We picked the following convention for docstrings:
- Use python type hints.
- Use sphinx format for docstrings, specifically: 
:param : and :return :, we are dropping :type : and :rtype:

**Comment by luisaforozco** [comment]
Regarding the dependencies, In [this commit](https://github.com/GrainLearning/grainLearning/commit/3dea7f43bfac89df3094d74ed82ec42073c8f1fa)  I created two groups of extras rnn and rnn_M1_macOS with the necessary dependencies (only difference is in tensorflow).
I tested in my machine `poetry install -E rnn_M1_macOS` and on Snellius `poetry install -E rnn`, and the dependencies are handled correctly.

**Comment by luisaforozco** [comment]
The installation of tensorflow for arm64 macOS requires some extra steps that cannot be handled from poetry. I think the best is to keep it separately: if an user has M1 macOS he/she will have to install tensorflow first on his own, and then he/she can install grainLearning on the same python environment.
