### ISSUE TITLE
Improving callback functions

### ISSUE THREAD

**Issue by Retiefasuarus** [GrainLearning/grainLearning#57]
I'd like to open a discussion on how we can improve callback functions:

1. The way simulation data is set is non-standard, or different from other optimization libraries (scipy etc.). A suggestion is to take parameters as an input and output simulation data.
2. In connection to 1, if more functionality is required. Should additional callback functions (error handling, etc, post or pre callback) may be introduced?
3. Located in the DynamicSystems class, it is not possible to access additional information from other classes (like inference)
4. If the user require special functionality, documention how it can be done and possible common cases should be made. For example writting a new `BayesianCalibration.run()` function.

**Comment by chyalexcheng** [comment]
> The way simulation data is set is non-standard, or different from other optimization libraries (scipy etc.). A suggestion is to take parameters as an input and output simulation data.
This is a good idea. What the `bayes_optimize` function returns can be the optimized values and uncertainty. If a user want the samples and the statistics they should use `dynamic_system`?
> In connection to 1, if more functionality is required. Should additional callback functions (error handling, etc, post or pre callback) may be introduced?
Error handling is definitely needed. If only a single job is pending, it should be killed.
> Located in the DynamicSystems class, it is not possible to access additional information from other classes (like inference)
That's annoying. Maybe we need a sim_manager outside DynamicSystem?
> If the user require special functionality, documention how it can be done and possible common cases should be made. For example writting a new BayesianCalibration.run() function.
Do you mean to define virtual functions to be overwritten by users?

**Comment by Retiefasuarus** [comment]
> This is a good idea. What the bayes_optimize function returns can be the optimized values and uncertainty. If a user want the samples and the statistics they should use dynamic_system?

I meant the ```run_sim(model,**kwargs)``` function can be slightly redesigned. 
The default should be 
```python 
def run_sim(params):
...
return sim_data
```
A user may want to include other input 

```python 
def run_sim(params, ctrl_data): 
...
```

 or

```python 
def run_sim(params, model): 
...
``` 

as optional input parameters. 

From a user input perspective, they may set in the config default as ```{"callback": run_sim, ..}``` or other versions ```{
"callback": {"function": run_sim, "include":["model", ctrl_data"]}}```.  Internally this can be done following a similar design as [scipy root finding](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.root.html)


> Error handling is definitely needed. If only a single job is pending, it should be killed.

I think this can only be done on a user side. Internally, we can add a way to handle unexpected input to grain learning (NaN)

> That's annoying. Maybe we need a sim_manager outside DynamicSystem?

I was thinking we can have it at the top level class under ```BayesianCalibration``` class.


> Do you mean to define virtual functions to be overwritten by users?

I meant something as described in my first answer.
